Controllers/FoodController.cs
using RestaurentManagementSystem_EF.Models;
using RestaurentManagementSystem_EF.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestaurentManagementSystem_EF.Controllers
{
    public class FoodController : Controller
    {
        // GET: Food
        public ActionResult Index(int? id)
        {
            var ctx = new Model1();

            var menuWisefoodQty = from p in ctx.foodItems
                                         group p by p.MenuId into g
                                         select new
                                         {
                                             g.FirstOrDefault().MenuId,
                                             Qty = g.Sum(s => s.Quantity)
                                         };
            var listMenu = (from c in ctx.Menus
                                join cwpq in menuWisefoodQty on c.MenuId equals cwpq.MenuId
                                select new VmMenu
                                {
                                    MenuName = c.MenuName,
                                    MenuId = cwpq.MenuId,
                                    Quantity = cwpq.Qty
                                }).ToList();
            var listFood = (from p in ctx.foodItems
                               join c in ctx.Menus on p.MenuId equals c.MenuId
                               where p.MenuId == id
                               select new VmFood
                               {
                                   MenuId = p.MenuId,
                                   MenuName = c.MenuName,
                                   ExpireDate = p.ExpireDate,
                                   ImagePath = p.ImagePath,
                                   Price = p.Price,
                                   ItemId = p.ItemId,
                                   FoodName = p.FoodName,
                                   Quantity = p.Quantity
                               }).ToList();

            var oMenuWiseFood = new VmMenuWiseFood();
            oMenuWiseFood.MenuList = listMenu;
            oMenuWiseFood.FoodList = listFood;
            oMenuWiseFood.MenuId = listFood.Count > 0 ? listFood[0].MenuId : 0;
            oMenuWiseFood.MenuName = listFood.Count > 0 ? listFood[0].MenuName : "";

            return View(oMenuWiseFood);
        }

        public ActionResult Create()
        {
            var model = new VmFoodMenu();
            var ctx = new Model1();
            model.MenuList = ctx.Menus.ToList();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(Menu model, string[] FoodName, decimal[] Price, int[] Quantity, DateTime[] ExpireDate, HttpPostedFileBase[] imgFile)
        {
            var ctx = new Model1();
            var oMenu = (from c in ctx.Menus where c.MenuName == model.MenuName.Trim() select c).FirstOrDefault();
            if (oMenu == null)
            {
                ctx.Menus.Add(model);
                ctx.SaveChanges();
            }
            else
            {
                model.MenuId = oMenu.MenuId;
            }

            var listFood = new List<FoodItem>();
            for (int i = 0; i < FoodName.Length; i++)
            {
                string imgPath = "";
                if (imgFile[i] != null && imgFile[i].ContentLength > 0)
                {
                    var fileName = Path.GetFileName(imgFile[i].FileName);
                    string fileLocation = Path.Combine(
                        Server.MapPath("~/uploads"), fileName);
                    imgFile[i].SaveAs(fileLocation);

                    imgPath = "/uploads/" + imgFile[i].FileName;
                }

                var newFood = new FoodItem();
                newFood.FoodName = FoodName[i];
                newFood.Quantity = Quantity[i];
                newFood.Price = Price[i];
                newFood.ExpireDate = ExpireDate[i];
                newFood.ImagePath = imgPath;
                newFood.Quantity = Quantity[i];
                newFood.MenuId = model.MenuId;
                listFood.Add(newFood);
            }
            ctx.foodItems.AddRange(listFood);
            ctx.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var ctx = new Model1();
            var oFood = (from p in ctx.foodItems
                            join c in ctx.Menus on p.MenuId equals c.MenuId
                            where p.ItemId == id
                            select new VmFood
                            {
                                MenuId = p.MenuId,
                                MenuName = c.MenuName,
                                ExpireDate = p.ExpireDate,
                                ImagePath = p.ImagePath,
                                Price = p.Price,
                                ItemId = p.ItemId,
                                FoodName = p.FoodName,
                                Quantity = p.Quantity
                            }).FirstOrDefault();
            oFood.MenuList = ctx.Menus.ToList(); // for showing category list in view
            return View(oFood);
        }

        [HttpPost]
        public ActionResult Edit(VmFood model)
        {
            var ctx = new Model1();

            string imgPath = "";
            if (model.ImgFile != null && model.ImgFile.ContentLength > 0)
            {
                var fileName = Path.GetFileName(model.ImgFile.FileName);
                string fileLocation = Path.Combine(
                    Server.MapPath("~/uploads"), fileName);
                model.ImgFile.SaveAs(fileLocation);

                imgPath = "/uploads/" + model.ImgFile.FileName;
            }

            var oFood = ctx.foodItems.Where(w => w.ItemId == model.ItemId).FirstOrDefault();
            if (oFood != null)
            {
                oFood.FoodName = model.FoodName;
                oFood.Quantity = model.Quantity;
                oFood.Price = model.Price;
                oFood.ExpireDate = model.ExpireDate;
                oFood.MenuId = model.MenuId;
                if (!string.IsNullOrEmpty(imgPath))
                {
                    var fileName = Path.GetFileName(oFood.ImagePath);
                    string fileLocation = Path.Combine(Server.MapPath("~/uploads"), fileName);
                    if (System.IO.File.Exists(fileLocation))
                    {
                        System.IO.File.Delete(fileLocation);
                    }
                }
                oFood.ImagePath = imgPath == "" ? oFood.ImagePath : imgPath;

                ctx.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        public ActionResult EditMultiple(int id)
        {
            var ctx = new Model1();
            var oMenuWiseFood = new VmMenuWiseFood();
            var listFood = (from p in ctx.foodItems
                               join c in ctx.Menus on p.MenuId equals c.MenuId
                               where p.MenuId == id
                               select new VmFood
                               {
                                   MenuId = p.MenuId,
                                   MenuName = c.MenuName,
                                   ExpireDate = p.ExpireDate,
                                   ImagePath = p.ImagePath,
                                   Price = p.Price,
                                   ItemId = p.ItemId,
                                   FoodName = p.FoodName,
                                   Quantity = p.Quantity
                               }).ToList();
            oMenuWiseFood.FoodList = listFood;
            // for showing category list in view
            oMenuWiseFood.MenuList = (from c in ctx.Menus
                                                 select new VmMenu
                                                 {
                                                     MenuId = c.MenuId,
                                                     MenuName = c.MenuName
                                                 }).ToList();
            oMenuWiseFood.MenuId = listFood.Count > 0 ? listFood[0].MenuId : 0;
            oMenuWiseFood.MenuName = listFood.Count > 0 ? listFood[0].MenuName : "";
            return View(oMenuWiseFood);
        }

        [HttpPost]
        public ActionResult EditMultiple(Menu model, int[] ItemId, string[] FoodName, decimal[] Price, int[] Quantity, DateTime[] ExpireDate, HttpPostedFileBase[] imgFile)
        {
            var ctx = new Model1();
            var listFood = new List<FoodItem>();
            for (int i = 0; i < FoodName.Length; i++)
            {
                if (ItemId[i] > 0)
                {
                    string imgPath = "";
                    if (imgFile[i] != null && imgFile[i].ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(imgFile[i].FileName);
                        string fileLocation = Path.Combine(
                            Server.MapPath("~/uploads"), fileName);
                        imgFile[i].SaveAs(fileLocation);

                        imgPath = "/uploads/" + imgFile[i].FileName;
                    }
                    int pid = ItemId[i];
                    var oFood = ctx.foodItems.Where(w => w.ItemId == pid).FirstOrDefault();
                    if (oFood != null)
                    {
                        oFood.FoodName = FoodName[i];
                        oFood.Quantity = Quantity[i];
                        oFood.Price = Price[i];
                        oFood.ExpireDate = ExpireDate[i];

Views/Food/Create.cshtml
@model RestaurentManagementSystem_EF.Models.ViewModels.VmFoodMenu
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Create Products</h2>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@using (Html.BeginForm("Create", "Food", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            Category:
            <input list="Menu" name="MenuName" id="MenuName" required autocomplete="off">
            <datalist id="Menu">
                @foreach (var item in Model.MenuList)
                {
                    <option value="@item.MenuName" />
                }
            </datalist>
        </div>
        <div class="form-group">
            <div id="ProData" class="Table">
                <div id="RowData" class="Row">
                    <input type="text" name="FoodName" placeholder="FoodName" />
                    <input type="text" name="Quantity" placeholder="Quantity" />
                    <input type="text" name="Price" placeholder="Price" />
                    <input type="date" name="ExpireDate" placeholder="ExpireDate" />
                    <input type="file" name="imgFile" placeholder="imgFile" />
                    <a id="addRow" href="#" class="btn btn-xs btn-success"><i>+</i></a><hr />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default">
            </div>
        </div>
    </div>
}
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script>

    $('#addRow').on('click', function () {
        $('#ProData').append('<div id="RowData" class="Row"><input type="text" name="FoodName" placeholder="FoodName" /><input type="text" name="Quantity" placeholder="Quantity" /><input type="text" name="Price" placeholder="Price" /><input type="date" name="ExpireDate" placeholder="ExpireDate" /><input type="file" name="imgFile" placeholder="imgFile" /><a id="deleteRow" href="#" class="btn btn-xs btn-danger"><i>-</i></a><hr /></div>');
        $('#ProData').addClass();
        return false; //prevent form submission
    });
    $('#ProData').on('click', '#deleteRow', function () {
        $(this).parent().remove();
        return false; //prevent form submission
    });
</script>

Views/Food/Edit.cshtml
@model RestaurentManagementSystem_EF.Models.ViewModels.VmFood
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var ExpireDate = Model.ExpireDate == null ? "" : Convert.ToDateTime(Model.ExpireDate).ToString("yyyy-MM-dd");

}

<h2>Edit Product</h2>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@using (Html.BeginForm("Edit", "Food", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            Category
            <select id="MenuId" name="MenuId" required>
                @foreach (var item in Model.MenuList)
                {
                    var Selected = item.MenuId == Model.MenuId ? "selected" : "";
                    <option value="@item.MenuId" @Selected>@item.MenuName</option>
                }
            </select>
        </div>
        <div class="form-group">
            <div id="ProData" class="Table">
                <div id="RowData" class="Row">
                    <input type="hidden" name="ItemId" value="@Model.ItemId" />
                    <input type="text" name="FoodName" placeholder="FoodName" value="@Model.FoodName" />
                    <input type="text" name="Quantity" placeholder="Quantity" value="@Model.Quantity" />
                    <input type="text" name="Price" placeholder="Price" value="@Model.Price" />
                    <input type="date" name="ExpireDate" placeholder="ExpireDate" value="@ExpireDate" />
                    <input type="file" name="imgFile" placeholder="imgFile" />
                    <img src="@Model.ImagePath" style="width:150px" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn btn-default">
            </div>
        </div>
    </div>
}

Views/Food/EditMultiple.cshtml
@model RestaurentManagementSystem_EF.Models.ViewModels.VmMenuWiseFood
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Edit Product</h2>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@using (Html.BeginForm("EditMultiple", "Food", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            Category
            <select id="MenuId" name="MenuId" required>
                @foreach (var item in Model.MenuList)
                {
                    var Selected = item.MenuId == Model.MenuId ? "selected" : "";
                    <option value="@item.MenuId" @Selected>@item.MenuName</option>
                }
            </select>
        </div>
        <div class="form-group">
            <div id="ProData" class="Table">
                <div id="RowData" class="Row">
                    <input type="hidden" name="ItemId" />
                    <input type="text" name="FoodName" placeholder="FoodName" />
                    <input type="text" name="Quantity" placeholder="Quantity" />
                    <input type="text" name="Price" placeholder="Price" />
                    <input type="date" name="ExpireDate" placeholder="ExpireDate" />
                    <input type="file" name="imgFile" placeholder="imgFile" />
                    <a id="addRow" href="#" class="btn btn-xs btn-success"><i>+</i></a><hr />
                </div>
                @foreach (var item in Model.FoodList)
                {
                    var ExpireDate = item.ExpireDate == null ? "" : Convert.ToDateTime(item.ExpireDate).ToString("yyyy-MM-dd");
                    <div id="RowData" class="Row">
                        <input type="hidden" name="ItemId" value="@item.ItemId" />
                        <input type="text" name="FoodName" placeholder="ProductName" value="@item.FoodName" />
                        <input type="text" name="Quantity" placeholder="Quantity" value="@item.Quantity" />
                        <input type="text" name="Price" placeholder="Price" value="@item.Price" />
                        <input type="date" name="ExpireDate" placeholder="ExpireDate" value="@ExpireDate" />
                        <input type="file" name="imgFile" placeholder="imgFile" />
                        <a id="deleteRow" href="#" class="btn btn-xs btn-danger"><i>-</i></a>
                        <img src="@item.ImagePath" style="width:150px" />
                        <hr />
                    </div>
                }
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn btn-default">
            </div>
        </div>
    </div>
}
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script>

    $('#addRow').on('click', function () {
        $('#ProData').append('<div id="RowData" class="Row"><input type="text" name="ProductName" placeholder="ProductName" /><input type="text" name="Quantity" placeholder="Quantity" /><input type="text" name="Price" placeholder="Price" /><input type="date" name="ExpireDate" placeholder="ExpireDate" /><input type="file" name="imgFile" placeholder="imgFile" /><a id="deleteRow" href="#" class="btn btn-xs btn-danger"><i>-</i></a><hr /></div>');
        $('#ProData').addClass();
        return false; //prevent form submission
    });
    $('#ProData').on('click', '#deleteRow', function () {
        $(this).parent().remove();
        return false; //prevent form submission
    });
</script>

Views/Food/Index.cshtml
@model RestaurentManagementSystem_EF.Models.ViewModels.VmMenuWiseFood
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-4">
        <h4>Menu</h4>
        <p>
            <a href="/Food/Create" class="btn btn-sm btn-success">Create New</a>
        </p>
        <table class="table">
            <tr>
                <th>
                    Menu
                </th>
                <th>
                    Avaiable Food Items
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.MenuList)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.MenuName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        <a href="/Food/Index?id=@item.MenuId" class="btn btn-sm btn-primary">Details</a> |
                        <a href="/Food/EditMultiple?id=@item.MenuId" class="btn btn-sm btn-warning">Edit</a>
                        <a href="/Food/DeleteMultiple?id=@item.MenuId" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure to delete this category with products?')">Delete</a>
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="col-md-8">
        <h4>Prdoucts of @Model.MenuName</h4>
        <p>
            <a href="/Food/Create" class="btn btn-sm btn-success">Create New</a>
        </p>
        <table class="table">
            <tr>
                <th>
                    Menu
                </th>
                <th>
                    Food Item
                </th>
                <th>
                    Price
                </th>
                <th>
                    ExpireDate
                </th>
                <th>
                    Quantity
                </th>
                <th>
                    ImagePath
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.FoodList)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.MenuName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FoodName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ExpireDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        <img src="@item.ImagePath" style="height:150px" />
                    </td>
                    <td>
                        <a href="/Food/Edit?id=@item.ItemId" class="btn btn-sm btn-warning">Edit</a> |
                        <a href="/Food/Delete?id=@item.ItemId" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure to delete this product?')">Delete</a>
                    </td>

                </tr>
            }
        </table>
    </div>
</div>